export const JOB_WATCH_BATCH_ID = "bay-area-watch-2026-07-24";

export const JOB_WATCH_ROLES = [
  {
    company: "Anthropic",
    title: "Marketing Events Lead, Brand",
    location: "San Francisco or New York · hybrid",
    sourceUrl: "https://job-boards.greenhouse.io/anthropic/jobs/5194529008",
    fitScore: 92,
    fitSummary: "Verified July 21, 2026. Strong alignment across end-to-end experiential production, budgets, vendors, agencies, creative direction, scalable processes, and post-event measurement. The listing requires extensive seniority and 30–40% travel.",
  },
  {
    company: "Google",
    title: "Senior Manager, Creative Solutions, YouTube Ads GTM",
    location: "San Bruno, San Francisco, Mountain View, or other listed U.S. offices",
    sourceUrl: "https://www.google.com/about/careers/applications/jobs/results/79561255219536582-senior-manager-creative-solutions-youtube-ads-gtm",
    fitScore: 91,
    fitSummary: "Verified July 21, 2026. Strong fit across advertising, creative solutions, operational leadership, cross-functional programs, stakeholder influence, and Marcos’s previous Google and agency experience. Ad-product commercialization and people leadership need clear evidence.",
  },
  {
    company: "OpenAI",
    title: "Growth Marketing, Creative System and Optimization",
    location: "San Francisco or New York · hybrid",
    sourceUrl: "https://jobs.ashbyhq.com/openai/02ee1352-9c8f-4efc-8127-d8f4eaed4474",
    fitScore: 88,
    fitSummary: "Verified July 21, 2026. Strong-to-moderate fit across creative systems, operational optimization, marketing communications delivery, and scaled production. Performance and growth-marketing experimentation need stronger evidence.",
  },
  {
    company: "Anthropic",
    title: "Marketing Events Lead, Enterprise",
    location: "San Francisco or New York · hybrid",
    sourceUrl: "https://job-boards.greenhouse.io/anthropic/jobs/5100274008",
    fitScore: 86,
    fitSummary: "Verified July 21, 2026. Good fit across complex events, budgets, vendors, agency management, process design, stakeholder communications, and post-event analysis. Enterprise pipeline and ABM ownership are the main evidence gaps; travel is substantial.",
  },
  {
    company: "OpenAI",
    title: "Business Affairs Manager",
    location: "San Francisco",
    sourceUrl: "https://jobs.ashbyhq.com/openai/b621a08b-e8fa-4829-b248-525880390040",
    fitScore: 72,
    fitSummary: "Verified July 21, 2026. Stretch opportunity with relevant agency liaison, production governance, budgeting, risk mitigation, and creative/legal coordination. Business-affairs contracting and production-rights experience require direct evidence.",
  },
  {
    company: "Google",
    title: "Product Strategy and Operations Lead, YouTube Strategic Analytics",
    location: "San Bruno",
    sourceUrl: "https://www.google.com/about/careers/applications/jobs/results/77997890345018054-product-strategy-and-operations-lead-youtube-strategic-analytics",
    fitScore: 69,
    fitSummary: "Verified July 21, 2026. Stretch fit across program operations, executive stakeholders, communications, process improvement, and prior Google experience. SQL, coding, and analytics are explicit requirements that need verified evidence.",
  },
  {
    company: "Highwire",
    title: "Director, Creative Production",
    location: "San Francisco hybrid or California remote",
    sourceUrl: "https://job-boards.greenhouse.io/highwire/jobs/4286062009",
    fitScore: 94,
    fitSummary: "Verified July 22, 2026. Excellent fit across agency production leadership, concurrent creative projects, staffing, budgets, vendors, process adoption, and video, motion, and experiential delivery. Listed compensation: $110K–$150K.",
  },
  {
    company: "George P. Johnson",
    title: "Senior Producer, Live Production",
    location: "San Francisco or Los Angeles hybrid",
    sourceUrl: "https://www.gpj.com/who-we-are/careers/7681093/",
    fitScore: 91,
    fitSummary: "Verified July 22, 2026. Strong fit across live events, launches, client and vendor management, RFPs, schedules, budgets, risk management, and experiential production. Technical live-staging depth should be highlighted. Listed compensation: $120K–$130K.",
  },
  {
    company: "e.l.f. Cosmetics",
    title: "Senior Manager, Brand Marketing",
    location: "Oakland or New York hybrid",
    sourceUrl: "https://jobs.lever.co/elfbeauty/d80b1a42-0803-4ea1-a2b9-35235afc7c92",
    fitScore: 87,
    fitSummary: "Verified July 22, 2026. Strong-to-moderate fit across global launches, creative campaigns, cross-functional execution, scalable playbooks, budgets, and stakeholder alignment. Beauty and CPG brand ownership is the principal gap. Listed compensation: $105K–$140K.",
  },
  {
    company: "Attentive",
    title: "Senior Specialist, Marketing Program Operations",
    location: "United States",
    sourceUrl: "https://job-boards.greenhouse.io/attentive/jobs/4280723009",
    fitScore: 86,
    fitSummary: "Verified July 22, 2026. Very close functional match across creative operations, briefs, resource capacity, integrated campaigns, launches, agency coordination, and PMO documentation, though likely below Marcos’s experience level. Listed compensation: $90K–$100K plus equity.",
  },
  {
    company: "Inizio Evoke",
    title: "Project Manager",
    location: "San Francisco hybrid or remote in Pacific time",
    sourceUrl: "https://www.inizioevoke.com/vacancy/inizioevoke/7905038?gh_jid=7905038",
    fitScore: 81,
    fitSummary: "Verified July 22, 2026. Strong responsibility match across agency project management, creative delivery, schedules, budgets, vendors, and risk management. Compensation and seniority appear below Marcos’s background. Listed compensation: $60K–$80K.",
  },
  {
    company: "Tubi",
    title: "Live Event Program & Integrated Project Manager",
    location: "Los Angeles hybrid · temporary, approximately six months",
    sourceUrl: "https://job-boards.greenhouse.io/tubitv/jobs/8065667",
    fitScore: 78,
    fitSummary: "Verified July 22, 2026. Strong sports-marketing alternative across live sports, integrated creative assets, sponsorship deliverables, events, budgets, schedules, and contingency planning. Location, temporary status, and broadcast-production requirements reduce the fit.",
  },
  {
    company: "Aventon",
    title: "Creative Producer",
    location: "Brea, California · on-site",
    sourceUrl: "https://jobs.lever.co/aventon/0027abdd-ae5b-4ff8-aa6d-39744a056db2",
    fitScore: 76,
    fitSummary: "Verified July 22, 2026. Strong creative-production match involving campaigns, branded content, photo and video production, vendors, budgets, workflow improvement, and athlete storytelling. Southern California on-site requirements are the main constraint.",
  },
  {
    company: "Hinge Health",
    title: "Lead Creative Program Manager",
    location: "San Francisco · hybrid",
    sourceUrl: "https://jobs.ashbyhq.com/hinge-health/c9c6716f-1f34-47b5-8986-efeea2b2be61",
    fitScore: 96,
    fitSummary: "Verified July 23, 2026. Excellent fit across creative operations, scalable workflows, AI-enabled processes, agency and vendor management, budgets, change management, and complex cross-functional programs.",
  },
  {
    company: "Hinge Health",
    title: "Sr. Lead Creative Ops",
    location: "San Francisco · hybrid",
    sourceUrl: "https://jobs.ashbyhq.com/hinge-health/6bc1fcea-3597-4a03-9ce8-cbe69685933f",
    fitScore: 95,
    fitSummary: "Verified July 23, 2026. Excellent senior-level alignment across resourcing, capacity planning, project systems, operational metrics, risk management, and AI-powered creative efficiency. Growth-performance creative evidence should be explicit.",
  },
  {
    company: "Perplexity",
    title: "Member of Creative Studio, Producer, Brand & Creative",
    location: "San Francisco, New York, or U.S. remote",
    sourceUrl: "https://jobs.ashbyhq.com/perplexity/678d1162-e650-4d6d-9532-b287255c00fb",
    fitScore: 95,
    fitSummary: "Verified July 23, 2026. Excellent fit as the operational backbone for brand campaigns, launches, shoots, and partnerships, with ownership of scopes, timelines, budgets, vendors, agencies, and cross-functional intake.",
  },
  {
    company: "Snap",
    title: "Senior Project Manager, Creative & Marketing",
    location: "San Francisco, Los Angeles, or New York · four office days weekly",
    sourceUrl: "https://careers.snap.com/job?id=R0046050",
    fitScore: 93,
    fitSummary: "Verified July 23, 2026; listing dated July 2, 2026. Strong direct fit across integrated creative projects, B2B, events, digital, video, social, forecasting, resourcing, process improvement, and stakeholder management.",
  },
  {
    company: "Whatnot",
    title: "Program Manager, In-house Performance Creative",
    location: "San Francisco, Los Angeles, New York, or Seattle · remote",
    sourceUrl: "https://jobs.ashbyhq.com/whatnot/1601046c-7313-4133-aea9-b72bb7a24237",
    fitScore: 88,
    fitSummary: "Verified July 23, 2026. Strong creative-operations match for building a high-volume creative-testing operating system. Performance-marketing experimentation and paid-growth measurement need clear evidence.",
  },
  {
    company: "Jack Morton Worldwide",
    title: "Executive Producer, Conferences",
    location: "San Francisco preferred or U.S. remote",
    sourceUrl: "https://job-boards.greenhouse.io/jackmortonworldwide/jobs/4309150009",
    fitScore: 89,
    fitSummary: "Verified July 23, 2026. Strong experiential-production fit across complex global programs, staffing, budgets, forecasting, vendors, creative feasibility, risk, and senior client relationships. Major B2B technology conference leadership must be proven.",
  },
  {
    company: "The Athletic",
    title: "Senior Manager, Video Production Operations",
    location: "United States · remote",
    sourceUrl: "https://jobs.lever.co/theathletic/b193f00d-359f-416a-9a02-af9876aaa2ca",
    fitScore: 84,
    fitSummary: "Verified July 23, 2026. Strong Sports-track alignment across global production operations, sponsorship integrations, budgets, team leadership, and major events. Compensation is low for the scope and hands-on editing-tool depth is required.",
  },
  {
    company: "Gantri",
    title: "Director of Marketing",
    location: "San Francisco, Los Angeles, or New York · remote",
    sourceUrl: "https://jobs.lever.co/Gantri/9c6c5974-0220-4e6f-a8e9-d2a9cbe4f3f2",
    fitScore: 82,
    fitSummary: "Verified July 23, 2026. Strong but ambitious fit combining brand strategy, creative execution, launches, agencies, partnerships, and marketing operating systems. Direct consumer-brand positioning and commercial-growth ownership need strong evidence.",
  },
] as const;
